### PR TITLE
percolator: Remove canGoCommit and canGoPrewrite.

### PR DESCRIPTION
**Pull request by foreverbell**
Previously, we use `canGoCommit` and `canGoPrewrite` to determine if we can advance to commit and prewrite phase. But these two operations involves cross-row transaction which is not supported by underlying RocksDB.

In fact, every time we pick one key that not locked or has stale lock, this operation only needs to be done for every key only once. So propose these solutions for these two operations.

* `canGoCommit`: maintain a key set pending for lock. Commit once the set is empty.
* `canGoPrewrite`: simply remove this operation. Transaction can either choose to clean up the lock or not when encounters a stale one.

### CODE REVIEW

**Comment by siddontang** [comment]
No invariant for pending?

**Comment by foreverbell** [comment]
I think it is unnecessary.

`pending` is maintaining the secondary keys that haven't been locked. But even it is locked, it can be reverted by other transactions.. so I think there isn't any good invariant for pending?

**Comment by siddontang** [comment]
LGTM

**Comment by IANTHEREAL** [comment]
LGTM

**Pull request merged**
